In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
df["species"].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [4]:
setosa = df[df['species'] == 'setosa']
versicolor = df[df['species'] == 'versicolor']
virginica = df[df['species'] == 'virginica']

In [5]:

setosa.mean(numeric_only=True)

sepal_length    5.006
sepal_width     3.428
petal_length    1.462
petal_width     0.246
dtype: float64

In [6]:
setosa.median(numeric_only=True)

sepal_length    5.0
sepal_width     3.4
petal_length    1.5
petal_width     0.2
dtype: float64

In [7]:
setosa.std(numeric_only=True)

sepal_length    0.352490
sepal_width     0.379064
petal_length    0.173664
petal_width     0.105386
dtype: float64

In [8]:
setosa.quantile([0.25, 0.50, 0.75], numeric_only=True)

      sepal_length  sepal_width  petal_length  petal_width
0.25           4.8        3.200         1.400          0.2
0.50           5.0        3.400         1.500          0.2
0.75           5.2        3.675         1.575          0.3

In [9]:
setosa.min(numeric_only=True)

sepal_length    4.3
sepal_width     2.3
petal_length    1.0
petal_width     0.1
dtype: float64

In [10]:
setosa.max(numeric_only=True)

sepal_length    5.8
sepal_width     4.4
petal_length    1.9
petal_width     0.6
dtype: float64

In [11]:
versicolor.mean(numeric_only=True)

sepal_length    5.936
sepal_width     2.770
petal_length    4.260
petal_width     1.326
dtype: float64

In [12]:
versicolor.median(numeric_only=True)

sepal_length    5.90
sepal_width     2.80
petal_length    4.35
petal_width     1.30
dtype: float64

In [13]:
versicolor.std(numeric_only=True)

sepal_length    0.516171
sepal_width     0.313798
petal_length    0.469911
petal_width     0.197753
dtype: float64

In [14]:
versicolor.quantile([0.25,0.50,0.75],numeric_only=True)

      sepal_length  sepal_width  petal_length  petal_width
0.25           5.6        2.525          4.00          1.2
0.50           5.9        2.800          4.35          1.3
0.75           6.3        3.000          4.60          1.5

In [15]:
versicolor.min(numeric_only=True)

sepal_length    4.9
sepal_width     2.0
petal_length    3.0
petal_width     1.0
dtype: float64

In [16]:
versicolor.max(numeric_only=True)

sepal_length    7.0
sepal_width     3.4
petal_length    5.1
petal_width     1.8
dtype: float64

In [17]:
virginica.mean(numeric_only=True)

sepal_length    6.588
sepal_width     2.974
petal_length    5.552
petal_width     2.026
dtype: float64

In [18]:
virginica.median(numeric_only=True)

sepal_length    6.50
sepal_width     3.00
petal_length    5.55
petal_width     2.00
dtype: float64

In [19]:

virginica.std(numeric_only=True)

sepal_length    0.635880
sepal_width     0.322497
petal_length    0.551895
petal_width     0.274650
dtype: float64

In [20]:

virginica.quantile([0.25,0.50,0.75],numeric_only=True)

      sepal_length  sepal_width  petal_length  petal_width
0.25         6.225        2.800         5.100          1.8
0.50         6.500        3.000         5.550          2.0
0.75         6.900        3.175         5.875          2.3

In [21]:

virginica.min(numeric_only=True)

sepal_length    4.9
sepal_width     2.2
petal_length    4.5
petal_width     1.4
dtype: float64

In [22]:

virginica.max(numeric_only=True)

sepal_length    7.9
sepal_width     3.8
petal_length    6.9
petal_width     2.5
dtype: float64